<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard1.3;netstandard2.0;net35;net40;net45;net46;net47</TargetFrameworks>
    <DebugType>full</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>
  <PropertyGroup>
    <Description>Discriminated Json Subtypes Converter implementation for .NET</Description>
    <Version>2.0.1</Version>
    <PackageTags>json converter subtype inheritance deserializeobject polymorphism</PackageTags>
    <AssemblyVersion>2.0.1.0</AssemblyVersion>
    <LangVersion>7</LangVersion>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>JsonSubTypes.Key.snk</AssemblyOriginatorKeyFile>
    <DelaySign>false</DelaySign>
    <FileVersion>2.0.1.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\"/>
    <None Include="..\LICENSE" Pack="true" PackagePath="\"/>
  </ItemGroup>
</Project>