image: Visual Studio 2022

environment:
  sonar_token:
    secure: 4M8z89LHqy9Rho8Mi4i7V0Ajz/7kvDYolVFH2V0GjK5VO5dseuv2Dja/qmKbio1I
  github_auth_token:
    secure: XUib5rF8Uxwk7S2umtsFEQ9t5G0p/J3G3PNpWLZuNIyw/zNufLDCge8C6QJRTzQw

init:
  - choco install opencover.portable
  - choco install codecov
  - choco install "sonarscanner-msbuild-net46" -y

build: off

build_script:
  - dotnet build JsonSubTypes.sln -c Release

test_script:
  - dotnet test JsonSubTypes.Text.Json.Tests/JsonSubTypes.Text.Json.Tests.csproj -c Release
  - dotnet test JsonSubTypes.Aot.Tests/JsonSubTypes.Aot.Tests.csproj -c Release
  - dotnet publish JsonSubTypes.Aot.Sample/JsonSubTypes.Aot.Sample.csproj -c Release -r win-x64 -p:StripSymbols=true
  - .\JsonSubTypes.Aot.Sample\bin\Release\net8.0\win-x64\publish\JsonSubTypes.Aot.Sample.exe
  - OpenCover.Console.exe -register:admin -target:"nunit3-console.exe" -targetargs:".\JsonSubTypes.Tests\bin\Release\net46\JsonSubTypes.Tests.dll --result:nunitTestResult.xml" -filter:"+[JsonSubTypes*]* -[JsonSubTypes.Tests]*" -output:".\MyProject_coverage.xml"
  - codecov -f "MyProject_coverage.xml"

artifacts:
  - path: 'JsonSubTypes\**\*.nupkg'
  - path: 'JsonSubTypes.Text.Json\**\*.nupkg'
  - path: 'JsonSubTypes.Aot\**\*.nupkg'

deploy:
  - provider: NuGet
    name: NuGet
    server: https://www.nuget.org/api/v2/package
    api_key:
      secure: xnIfMdyjVdTmzfvREY0gxpxV2dviHjlA3gA+bDNcPgrxKrP5UGe6n7qtexJoSP90
    artifact: /JsonSubTypes.*\.nupkg/
    on:
      branch: master
