#nullable enable
using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace JsonSubTypes.Text.Json.Aot.Generated
{
    /// <summary>Generated by JsonSubTypes.Text.Json.Aot. Compiled converter for global::JsonSubTypes.Text.Json.Aot.Generated.TestDomain.DynamicShape.</summary>
    public sealed class DynamicShapeJsonSubTypesConverter : JsonSubTypesAotValueConverterBase<global::JsonSubTypes.Text.Json.Aot.Generated.TestDomain.DynamicShape>
    {
        private const string DiscriminatorPropertyNameValue = "kind";
        protected override string DiscriminatorPropertyName => DiscriminatorPropertyNameValue;

        protected override System.Collections.Generic.Dictionary<System.Type, System.Action<Utf8JsonWriter, JsonSerializerOptions>> DiscriminatorWriters { get; } = new System.Collections.Generic.Dictionary<System.Type, System.Action<Utf8JsonWriter, JsonSerializerOptions>>
        {
            [typeof(global::JsonSubTypes.Text.Json.Aot.Generated.TestDomain.DynamicCat)] = static (writer, options) => writer.WriteStringValue("cat")
        };

        protected override Type SelectType(JsonElement root, JsonSerializerOptions options)
        {
            if (!TryGetValueInJson(root, DiscriminatorPropertyNameValue, options, out JsonElement discriminator))
            {
                return typeof(global::JsonSubTypes.Text.Json.Aot.Generated.TestDomain.DynamicShape);
            }
            Type? staticType = ResolveStaticType(discriminator);
            if (staticType != null)
            {
                return staticType;
            }
            if (TryGetDynamicType(discriminator, out Type? dynamicType))
            {
                return dynamicType!;
            }
            if (CustomTypeNameResolver is not null)
            {
                Type? customType = CustomTypeNameResolver(GetDiscriminatorKey(discriminator));
                if (customType != null)
                {
                    return customType;
                }
            }
            return typeof(global::JsonSubTypes.Text.Json.Aot.Generated.TestDomain.DynamicShape);
        }

        private static Type? ResolveStaticType(JsonElement discriminator)
        {
            switch (discriminator.ValueKind)
            {
                case JsonValueKind.String:
                    switch (discriminator.GetString())
                    {
                        case "cat": return typeof(global::JsonSubTypes.Text.Json.Aot.Generated.TestDomain.DynamicCat);
                    }
                    break;
            }
            return null;
        }

        protected override void WriteBaseObject(Utf8JsonWriter writer, global::JsonSubTypes.Text.Json.Aot.Generated.TestDomain.DynamicShape value, JsonSerializerOptions options)
        {
            writer.WriteStartObject();
            string nameAge = "Age";
            if (options.PropertyNamingPolicy != null && true)
            {
                nameAge = options.PropertyNamingPolicy.ConvertName(nameAge);
            }
            writer.WritePropertyName(nameAge);
            JsonSerializer.Serialize(writer, value.Age, options.GetTypeInfo(typeof(int)));
            string nameComputed = "Computed";
            if (options.PropertyNamingPolicy != null && true)
            {
                nameComputed = options.PropertyNamingPolicy.ConvertName(nameComputed);
            }
            writer.WritePropertyName(nameComputed);
            JsonSerializer.Serialize(writer, value.Computed, options.GetTypeInfo(typeof(string)));
            if (value.Nickname != null)
            {
                string nameNickname = "Nickname";
                if (options.PropertyNamingPolicy != null && true)
                {
                    nameNickname = options.PropertyNamingPolicy.ConvertName(nameNickname);
                }
                writer.WritePropertyName(nameNickname);
                JsonSerializer.Serialize(writer, value.Nickname, options.GetTypeInfo(typeof(string)));
            }
            writer.WriteEndObject();
        }
        protected override global::JsonSubTypes.Text.Json.Aot.Generated.TestDomain.DynamicShape DeserializeBase(JsonElement root, JsonSerializerOptions options)
        {
            global::JsonSubTypes.Text.Json.Aot.Generated.TestDomain.DynamicShape instance = new global::JsonSubTypes.Text.Json.Aot.Generated.TestDomain.DynamicShape();
            if (TryGetProperty(root, "Age", options, out JsonElement AgeValue))
            {
                instance.Age = (int)JsonSerializer.Deserialize(AgeValue.GetRawText(), options.GetTypeInfo(typeof(int)))!;
            }
            if (TryGetProperty(root, "Nickname", options, out JsonElement NicknameValue))
            {
                instance.Nickname = (string)JsonSerializer.Deserialize(NicknameValue.GetRawText(), options.GetTypeInfo(typeof(string)))!;
            }
            return instance;
        }
        protected override bool TryWriteNestedObject(Utf8JsonWriter writer, global::JsonSubTypes.Text.Json.Aot.Generated.TestDomain.DynamicShape value, Type runtimeType, JsonSerializerOptions options)
        {
            return false;
        }
    }
}