#nullable enable

namespace JsonSubTypes.Text.Json.Aot.Generated
{
    /// <summary>Generated by JsonSubTypes.Text.Json.Aot. Shared converter instances to add to JsonSerializerOptions.Converters.</summary>
    public static class JsonSubTypesAotConverters
    {
        public static readonly AnimalJsonSubTypesConverter Animal = new AnimalJsonSubTypesConverter();
        public static readonly PersonJsonSubTypesConverter Person = new PersonJsonSubTypesConverter();
        public static readonly GadgetJsonSubTypesConverter Gadget = new GadgetJsonSubTypesConverter();
        public static readonly DottedGadgetJsonSubTypesConverter DottedGadget = new DottedGadgetJsonSubTypesConverter();
        public static readonly PayloadJsonSubTypesConverter Payload = new PayloadJsonSubTypesConverter();
        public static readonly GameJsonSubTypesConverter Game = new GameJsonSubTypesConverter();
    }
}