#nullable enable
using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace JsonSubTypes.Text.Json.Aot.Generated
{
    /// <summary>Generated by JsonSubTypes.Text.Json.Aot. Compiled converter for global::JsonSubTypes.Text.Json.Aot.Generated.TestDomain.NullDiscriminatorAnimal.</summary>
    public sealed class NullDiscriminatorAnimalJsonSubTypesConverter : JsonSubTypesAotValueConverterBase<global::JsonSubTypes.Text.Json.Aot.Generated.TestDomain.NullDiscriminatorAnimal>
    {
        private const string DiscriminatorPropertyNameValue = "type";
        protected override string DiscriminatorPropertyName => DiscriminatorPropertyNameValue;

        protected override System.Collections.Generic.Dictionary<System.Type, System.Action<Utf8JsonWriter, JsonSerializerOptions>> DiscriminatorWriters { get; } = new System.Collections.Generic.Dictionary<System.Type, System.Action<Utf8JsonWriter, JsonSerializerOptions>>
        {
            [typeof(global::JsonSubTypes.Text.Json.Aot.Generated.TestDomain.NullDiscriminatorAnimal)] = static (writer, options) => writer.WriteNullValue(),
            [typeof(global::JsonSubTypes.Text.Json.Aot.Generated.TestDomain.Deer)] = static (writer, options) => writer.WriteStringValue("deer")
        };

        protected override Type SelectType(JsonElement root, JsonSerializerOptions options)
        {
            if (!TryGetValueInJson(root, DiscriminatorPropertyNameValue, options, out JsonElement discriminator))
            {
                return typeof(global::JsonSubTypes.Text.Json.Aot.Generated.TestDomain.NullDiscriminatorAnimal);
            }
            Type? staticType = ResolveStaticType(discriminator);
            if (staticType != null)
            {
                return staticType;
            }
            if (TryGetDynamicType(discriminator, out Type? dynamicType))
            {
                return dynamicType!;
            }
            if (CustomTypeNameResolver is not null)
            {
                Type? customType = CustomTypeNameResolver(GetDiscriminatorKey(discriminator));
                if (customType != null)
                {
                    return customType;
                }
            }
            return typeof(global::JsonSubTypes.Text.Json.Aot.Generated.TestDomain.NullDiscriminatorAnimal);
        }

        private static Type? ResolveStaticType(JsonElement discriminator)
        {
            switch (discriminator.ValueKind)
            {
                case JsonValueKind.Null:
                    return typeof(global::JsonSubTypes.Text.Json.Aot.Generated.TestDomain.NullDiscriminatorAnimal);
                case JsonValueKind.String:
                    switch (discriminator.GetString())
                    {
                        case "deer": return typeof(global::JsonSubTypes.Text.Json.Aot.Generated.TestDomain.Deer);
                    }
                    break;
            }
            return null;
        }

        protected override void WriteBaseObject(Utf8JsonWriter writer, global::JsonSubTypes.Text.Json.Aot.Generated.TestDomain.NullDiscriminatorAnimal value, JsonSerializerOptions options)
        {
            writer.WriteStartObject();
            string nameAge = "Age";
            if (options.PropertyNamingPolicy != null && true)
            {
                nameAge = options.PropertyNamingPolicy.ConvertName(nameAge);
            }
            writer.WritePropertyName(nameAge);
            JsonSerializer.Serialize(writer, value.Age, options.GetTypeInfo(typeof(int)));
            writer.WriteEndObject();
        }
        protected override global::JsonSubTypes.Text.Json.Aot.Generated.TestDomain.NullDiscriminatorAnimal DeserializeBase(JsonElement root, JsonSerializerOptions options)
        {
            global::JsonSubTypes.Text.Json.Aot.Generated.TestDomain.NullDiscriminatorAnimal instance = new global::JsonSubTypes.Text.Json.Aot.Generated.TestDomain.NullDiscriminatorAnimal();
            if (TryGetProperty(root, "Age", options, out JsonElement AgeValue))
            {
                instance.Age = (int)JsonSerializer.Deserialize(AgeValue.GetRawText(), options.GetTypeInfo(typeof(int)))!;
            }
            return instance;
        }
        protected override bool TryWriteNestedObject(Utf8JsonWriter writer, global::JsonSubTypes.Text.Json.Aot.Generated.TestDomain.NullDiscriminatorAnimal value, Type runtimeType, JsonSerializerOptions options)
        {
            return false;
        }
    }
}