#nullable enable
using System;
using System.Linq;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace JsonSubTypes.Text.Json.Aot.Generated
{
    /// <summary>Generated by JsonSubTypes.Text.Json.Aot. Compiled converter for global::JsonSubTypes.Text.Json.Aot.Generated.TestDomain.Person.</summary>
    public sealed class PersonJsonSubTypesConverter : JsonSubTypesAotConverterBase<global::JsonSubTypes.Text.Json.Aot.Generated.TestDomain.Person>
    {
        protected override Type SelectType(JsonElement root, JsonSerializerOptions options)
        {
            System.Collections.Generic.HashSet<Type> matches = new System.Collections.Generic.HashSet<Type>();
        if (root.TryGetProperty("JobTitle", out _))
        {
            matches.Add(typeof(global::JsonSubTypes.Text.Json.Aot.Generated.TestDomain.Employee));
        }
        if (root.TryGetProperty("Skill", out _))
        {
            matches.Add(typeof(global::JsonSubTypes.Text.Json.Aot.Generated.TestDomain.Artist));
        }
            if (matches.Count == 1)
            {
                return matches.First();
            }
            if (matches.Count > 1)
            {
                throw new JsonException("Ambiguous type resolution, expected only one type but got: " + string.Join(", ", matches.Select(t => t.FullName)));
            }
            return typeof(global::JsonSubTypes.Text.Json.Aot.Generated.TestDomain.Person);
        }

        protected override void WriteBaseObject(Utf8JsonWriter writer, global::JsonSubTypes.Text.Json.Aot.Generated.TestDomain.Person value, JsonSerializerOptions options)
        {
            writer.WriteStartObject();
            string nameFirstName = "FirstName";
            if (options.PropertyNamingPolicy != null && true)
            {
                nameFirstName = options.PropertyNamingPolicy.ConvertName(nameFirstName);
            }
            writer.WritePropertyName(nameFirstName);
            JsonSerializer.Serialize(writer, value.FirstName, options.GetTypeInfo(typeof(string)));
            writer.WriteEndObject();
        }
        protected override global::JsonSubTypes.Text.Json.Aot.Generated.TestDomain.Person DeserializeBase(JsonElement root, JsonSerializerOptions options)
        {
            global::JsonSubTypes.Text.Json.Aot.Generated.TestDomain.Person instance = new global::JsonSubTypes.Text.Json.Aot.Generated.TestDomain.Person();
            if (TryGetProperty(root, "FirstName", options, out JsonElement FirstNameValue))
            {
                instance.FirstName = (string)JsonSerializer.Deserialize(FirstNameValue.GetRawText(), options.GetTypeInfo(typeof(string)))!;
            }
            return instance;
        }
        protected override bool TryWriteNestedObject(Utf8JsonWriter writer, global::JsonSubTypes.Text.Json.Aot.Generated.TestDomain.Person value, Type runtimeType, JsonSerializerOptions options)
        {
            return false;
        }
    }
}