<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <PropertyGroup>
    <Description>Discriminated Json Subtypes Converter implementation for System.Text.Json</Description>
    <Version>1.0.0-rc.3</Version>
    <PackageTags>json converter subtype inheritance deserializeobject polymorphism System.Text.Json</PackageTags>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>JsonSubTypes.Key.snk</AssemblyOriginatorKeyFile>
    <DelaySign>false</DelaySign>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\"/>
    <None Include="..\LICENSE" Pack="true" PackagePath="\"/>
  </ItemGroup>

</Project>
