#nullable enable
using System;
using System.IO;
using System.Linq;
using NUnit.Framework;

namespace JsonSubTypes.Text.Json.Aot.Generator.Tests
{
    // Golden-master test: runs the generator over the committed test domain and
    // compares every produced file against the committed golden-master files. Any change
    // in the generator's output breaks this test, forcing a conscious regeneration.
    [TestFixture]
    public class GoldenMasterTests
    {
        private const string DomainPath = "JsonSubTypes.Text.Json.Aot.Generated/TestDomain.cs";
        private const string GeneratedDir = "JsonSubTypes.Text.Json.Aot.Generated/GoldenMaster";

        private static string FindRepoRoot()
        {
            DirectoryInfo? dir = new DirectoryInfo(AppContext.BaseDirectory);
            while (dir != null && !File.Exists(Path.Combine(dir.FullName, "JsonSubTypes.sln")))
            {
                dir = dir.Parent;
            }
            return dir?.FullName ?? throw new DirectoryNotFoundException("Repo root not found");
        }

        [Test]
        public void GeneratedFiles_MatchCurrentGeneratorOutput()
        {
            string root = FindRepoRoot();
            string domain = File.ReadAllText(Path.Combine(root, DomainPath));
            string generatedDir = Path.Combine(root, GeneratedDir);

            GeneratorRun run = GeneratorDriverRunner.GetRun(domain);

            var produced = run.DriverResults.Results
                .SelectMany(r => r.GeneratedSources)
                .ToDictionary(s => s.HintName, s => s.SourceText.ToString());

            // Every committed .cs file must exist in the current output and match
            // exactly. The generator names its output *.g.cs; the committed golden
            // master drops that suffix so Sonar analyzes them as regular sources.
            string[] committed = Directory.GetFiles(generatedDir, "*.cs", SearchOption.AllDirectories);

            TestContext.WriteLine("PRODUCED: " + string.Join(", ", produced.Keys.OrderBy(k => k)));
            TestContext.WriteLine("COMMITTED: " + string.Join(", ", committed.Select(f => Path.GetFileName(f)).OrderBy(k => k)));

            Assert.That(produced.Count, Is.EqualTo(committed.Length),
                "Produced " + produced.Count + " files but " + committed.Length + " are committed");

            foreach (string committedFile in committed)
            {
                string committedName = Path.GetFileName(committedFile);
                string hintName = committedName.Replace(".cs", "") + ".g.cs";
                string committedText = NormalizeGeneratedCode(File.ReadAllText(committedFile));
                Assert.That(produced.ContainsKey(hintName), Is.True,
                    "Generator no longer produces committed file " + committedName);

                string producedText = NormalizeGeneratedCode(produced[hintName]);
                Assert.That(producedText, Is.EqualTo(committedText),
                    "Generator output differs from committed " + committedName +
                    ".\nRegenerate with: dotnet build JsonSubTypes.Text.Json.Aot.Generated -p:EmitCompilerGeneratedFiles=true");
            }

            // No extra files produced that are not committed.
            foreach (string hintName in produced.Keys)
            {
                string committedName = hintName.EndsWith(".g.cs") ? hintName.Replace(".g.cs", ".cs") : hintName;
                Assert.That(committed.Any(f => Path.GetFileName(f) == committedName), Is.True,
                    "Generator produces " + hintName + " but it is not committed");
            }
        }

        // Compare the generated text without the "generated code" markers, so a change
        // in the marker lines alone does not break the golden master.
        private static string NormalizeGeneratedCode(string text)
        {
            string[] lines = text.Replace("\r\n", "\n").Split('\n');
            var filtered = lines.Where(l =>
                !l.Trim().StartsWith("// <auto-generated/>") &&
                !l.Trim().Contains("global::System.CodeDom.Compiler.GeneratedCode"));
            return string.Join("\n", filtered).Trim();
        }
    }
}
