#nullable enable
using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace JsonSubTypes.Aot.Generated
{
    /// <summary>Generated by JsonSubTypes.Aot. Compiled converter for global::JsonSubTypes.Aot.Generated.TestDomain.DottedGadget.</summary>
    public sealed class DottedGadgetJsonSubTypesConverter : JsonSubTypesAotValueConverterBase<global::JsonSubTypes.Aot.Generated.TestDomain.DottedGadget>
    {
        protected override string DiscriminatorPropertyName => "nested.type";

        protected override System.Collections.Generic.Dictionary<System.Type, System.Action<Utf8JsonWriter, JsonSerializerOptions>> DiscriminatorWriters { get; } = new System.Collections.Generic.Dictionary<System.Type, System.Action<Utf8JsonWriter, JsonSerializerOptions>>
        {
            [typeof(global::JsonSubTypes.Aot.Generated.TestDomain.DottedElectronic)] = static (writer, options) => writer.WriteStringValue("electronic")
        };

        protected override Type SelectType(JsonElement root, JsonSerializerOptions options)
        {
    if (TryGetValueInJson(root, "nested.type", options, out JsonElement discriminator))
    {

    if (discriminator.ValueKind == JsonValueKind.String)
    {
        switch (discriminator.GetString())
        {
                        case "electronic": return typeof(global::JsonSubTypes.Aot.Generated.TestDomain.DottedElectronic);
        }
    }

        if (TryGetDynamicType(discriminator, out Type? dynamicType))
        {
            return dynamicType!;
        }
        if (CustomTypeNameResolver is not null)
        {
            Type? customType = CustomTypeNameResolver(GetDiscriminatorKey(discriminator));
            if (customType != null)
            {
                return customType;
            }
        }
        return typeof(global::JsonSubTypes.Aot.Generated.TestDomain.DottedGadget);
    }
    return typeof(global::JsonSubTypes.Aot.Generated.TestDomain.DottedGadget);
        }

        protected override void WriteBaseObject(Utf8JsonWriter writer, global::JsonSubTypes.Aot.Generated.TestDomain.DottedGadget value, JsonSerializerOptions options)
        {
            writer.WriteStartObject();
    string nameAge = "Age";
    if (options.PropertyNamingPolicy != null && true)
    {
        nameAge = options.PropertyNamingPolicy.ConvertName(nameAge);
    }
    writer.WritePropertyName(nameAge);
    JsonSerializer.Serialize(writer, value.Age, options.GetTypeInfo(typeof(int)));
            writer.WriteEndObject();
        }
        protected override global::JsonSubTypes.Aot.Generated.TestDomain.DottedGadget DeserializeBase(JsonElement root, JsonSerializerOptions options)
        {
            global::JsonSubTypes.Aot.Generated.TestDomain.DottedGadget instance = new global::JsonSubTypes.Aot.Generated.TestDomain.DottedGadget();
    if (TryGetProperty(root, "Age", options, out JsonElement AgeValue))
    {
        instance.Age = (int)JsonSerializer.Deserialize(AgeValue.GetRawText(), options.GetTypeInfo(typeof(int)))!;
    }
            return instance;
        }
        protected override bool TryWriteNestedObject(Utf8JsonWriter writer, global::JsonSubTypes.Aot.Generated.TestDomain.DottedGadget value, Type runtimeType, JsonSerializerOptions options)
        {
            return false;
        }
    }
}