#nullable enable
using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace JsonSubTypes.Aot.Generated
{
    /// <summary>Generated by JsonSubTypes.Aot. Compiled converter for global::JsonSubTypes.Aot.Generated.TestDomain.Gadget.</summary>
    public sealed class GadgetJsonSubTypesConverter : JsonSubTypesAotValueConverterBase<global::JsonSubTypes.Aot.Generated.TestDomain.Gadget>
    {
        protected override string DiscriminatorPropertyName => "kind";

        protected override System.Collections.Generic.Dictionary<System.Type, System.Action<Utf8JsonWriter, JsonSerializerOptions>> DiscriminatorWriters { get; } = new System.Collections.Generic.Dictionary<System.Type, System.Action<Utf8JsonWriter, JsonSerializerOptions>>
        {
            [typeof(global::JsonSubTypes.Aot.Generated.TestDomain.ElectronicCat)] = static (writer, options) => writer.WriteRawValue(JsonSerializer.Serialize(global::JsonSubTypes.Aot.Generated.TestDomain.GadgetKind.ElectronicCat, options.GetTypeInfo(typeof(global::JsonSubTypes.Aot.Generated.TestDomain.GadgetKind))))
        };


        protected override Type SelectType(JsonElement root, JsonSerializerOptions options)
        {
    if (TryGetValueInJson(root, "kind", options, out JsonElement discriminator))
    {

    if (discriminator.ValueKind == JsonValueKind.String)
    {
        switch (discriminator.GetString())
        {
                        case "ElectronicCat": return typeof(global::JsonSubTypes.Aot.Generated.TestDomain.ElectronicCat);
        }
    }
    if (discriminator.ValueKind == JsonValueKind.Number)
    {
        switch (discriminator.GetRawText())
        {
                        case "0": return typeof(global::JsonSubTypes.Aot.Generated.TestDomain.ElectronicCat);
        }
    }
        if (TryGetDynamicType(discriminator, out Type? dynamicType))
        {
            return dynamicType!;
        }
        if (CustomTypeNameResolver is not null)
        {
            Type? customType = CustomTypeNameResolver(GetDiscriminatorKey(discriminator));
            if (customType != null)
            {
                return customType;
            }
        }
        return typeof(global::JsonSubTypes.Aot.Generated.TestDomain.Gadget);
    }
    return typeof(global::JsonSubTypes.Aot.Generated.TestDomain.Gadget);
        }

        protected override void WriteBaseObject(Utf8JsonWriter writer, global::JsonSubTypes.Aot.Generated.TestDomain.Gadget value, JsonSerializerOptions options)
        {
            writer.WriteStartObject();
    string nameAge = "Age";
    if (options.PropertyNamingPolicy != null && true)
    {
        nameAge = options.PropertyNamingPolicy.ConvertName(nameAge);
    }
    writer.WritePropertyName(nameAge);
    JsonSerializer.Serialize(writer, value.Age, options.GetTypeInfo(typeof(int)));
            writer.WriteEndObject();
        }
        protected override global::JsonSubTypes.Aot.Generated.TestDomain.Gadget DeserializeBase(JsonElement root, JsonSerializerOptions options)
        {
            global::JsonSubTypes.Aot.Generated.TestDomain.Gadget instance = new global::JsonSubTypes.Aot.Generated.TestDomain.Gadget();
    if (TryGetProperty(root, "Age", options, out JsonElement AgeValue))
    {
        instance.Age = (int)JsonSerializer.Deserialize(AgeValue.GetRawText(), options.GetTypeInfo(typeof(int)))!;
    }
            return instance;
        }
        protected override bool TryWriteNestedObject(Utf8JsonWriter writer, global::JsonSubTypes.Aot.Generated.TestDomain.Gadget value, Type runtimeType, JsonSerializerOptions options)
        {

            return false;
        }
    }
}