#nullable enable
using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace JsonSubTypes.Aot.Generated
{
    /// <summary>Generated by JsonSubTypes.Aot. Compiled converter for global::JsonSubTypes.Aot.Generated.TestDomain.Game.</summary>
    public sealed class GameJsonSubTypesConverter : JsonSubTypesAotValueConverterBase<global::JsonSubTypes.Aot.Generated.TestDomain.Game>
    {
        private const string DiscriminatorPropertyNameValue = "$GameKind";
        protected override string DiscriminatorPropertyName => DiscriminatorPropertyNameValue;

        protected override System.Collections.Generic.Dictionary<System.Type, System.Action<Utf8JsonWriter, JsonSerializerOptions>> DiscriminatorWriters { get; } = new System.Collections.Generic.Dictionary<System.Type, System.Action<Utf8JsonWriter, JsonSerializerOptions>>
        {
            [typeof(global::JsonSubTypes.Aot.Generated.TestDomain.Run)] = static (writer, options) => writer.WriteRawValue(JsonSerializer.Serialize(global::JsonSubTypes.Aot.Generated.TestDomain.GameDiscriminator.RUN, options.GetTypeInfo(typeof(global::JsonSubTypes.Aot.Generated.TestDomain.GameDiscriminator)))),
            [typeof(global::JsonSubTypes.Aot.Generated.TestDomain.Walk)] = static (writer, options) => writer.WriteRawValue(JsonSerializer.Serialize(global::JsonSubTypes.Aot.Generated.TestDomain.GameDiscriminator.WALK, options.GetTypeInfo(typeof(global::JsonSubTypes.Aot.Generated.TestDomain.GameDiscriminator))))
        };

        protected override Type SelectType(JsonElement root, JsonSerializerOptions options)
        {
            if (!TryGetValueInJson(root, DiscriminatorPropertyNameValue, options, out JsonElement discriminator))
            {
                return typeof(global::JsonSubTypes.Aot.Generated.TestDomain.Game);
            }
            Type? staticType = ResolveStaticType(discriminator);
            if (staticType != null)
            {
                return staticType;
            }
            if (TryGetDynamicType(discriminator, out Type? dynamicType))
            {
                return dynamicType!;
            }
            if (CustomTypeNameResolver is not null)
            {
                Type? customType = CustomTypeNameResolver(GetDiscriminatorKey(discriminator));
                if (customType != null)
                {
                    return customType;
                }
            }
            return typeof(global::JsonSubTypes.Aot.Generated.TestDomain.Game);
        }

        private static Type? ResolveStaticType(JsonElement discriminator)
        {
            switch (discriminator.ValueKind)
            {
                case JsonValueKind.String:
                    switch (discriminator.GetString())
                    {
                        case "RUN": return typeof(global::JsonSubTypes.Aot.Generated.TestDomain.Run);
                        case "WALK": return typeof(global::JsonSubTypes.Aot.Generated.TestDomain.Walk);
                    }
                    break;
                case JsonValueKind.Number:
                    switch (discriminator.GetRawText())
                    {
                        case "0": return typeof(global::JsonSubTypes.Aot.Generated.TestDomain.Run);
                        case "1": return typeof(global::JsonSubTypes.Aot.Generated.TestDomain.Walk);
                    }
                    break;
            }
            return null;
        }

        protected override void WriteBaseObject(Utf8JsonWriter writer, global::JsonSubTypes.Aot.Generated.TestDomain.Game value, JsonSerializerOptions options)
        {
            writer.WriteStartObject();

            writer.WriteEndObject();
        }
        protected override global::JsonSubTypes.Aot.Generated.TestDomain.Game DeserializeBase(JsonElement root, JsonSerializerOptions options)
        {
            global::JsonSubTypes.Aot.Generated.TestDomain.Game instance = new global::JsonSubTypes.Aot.Generated.TestDomain.Game();

            return instance;
        }
        protected override bool TryWriteNestedObject(Utf8JsonWriter writer, global::JsonSubTypes.Aot.Generated.TestDomain.Game value, Type runtimeType, JsonSerializerOptions options)
        {
            return false;
        }
    }
}