#nullable enable
using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace JsonSubTypes.Aot.Generated
{
    /// <summary>Generated by JsonSubTypes.Aot. Compiled converter for global::JsonSubTypes.Aot.Generated.TestDomain.Game.</summary>
    public sealed class GameJsonSubTypesConverter : JsonSubTypesAotValueConverterBase<global::JsonSubTypes.Aot.Generated.TestDomain.Game>
    {
        protected override string DiscriminatorPropertyName => "$GameKind";

        protected override System.Collections.Generic.Dictionary<System.Type, System.Action<Utf8JsonWriter, JsonSerializerOptions>> DiscriminatorWriters { get; } = new System.Collections.Generic.Dictionary<System.Type, System.Action<Utf8JsonWriter, JsonSerializerOptions>>
        {
            [typeof(global::JsonSubTypes.Aot.Generated.TestDomain.Run)] = static (writer, options) => writer.WriteRawValue(JsonSerializer.Serialize(global::JsonSubTypes.Aot.Generated.TestDomain.GameDiscriminator.RUN, options.GetTypeInfo(typeof(global::JsonSubTypes.Aot.Generated.TestDomain.GameDiscriminator)))),
            [typeof(global::JsonSubTypes.Aot.Generated.TestDomain.Walk)] = static (writer, options) => writer.WriteRawValue(JsonSerializer.Serialize(global::JsonSubTypes.Aot.Generated.TestDomain.GameDiscriminator.WALK, options.GetTypeInfo(typeof(global::JsonSubTypes.Aot.Generated.TestDomain.GameDiscriminator))))
        };


        protected override Type SelectType(JsonElement root, JsonSerializerOptions options)
        {
    if (TryGetValueInJson(root, "$GameKind", options, out JsonElement discriminator))
    {

    if (discriminator.ValueKind == JsonValueKind.String)
    {
        switch (discriminator.GetString())
        {
                        case "RUN": return typeof(global::JsonSubTypes.Aot.Generated.TestDomain.Run);
                        case "WALK": return typeof(global::JsonSubTypes.Aot.Generated.TestDomain.Walk);
        }
    }
    if (discriminator.ValueKind == JsonValueKind.Number)
    {
        switch (discriminator.GetRawText())
        {
                        case "0": return typeof(global::JsonSubTypes.Aot.Generated.TestDomain.Run);
                        case "1": return typeof(global::JsonSubTypes.Aot.Generated.TestDomain.Walk);
        }
    }
        if (TryGetDynamicType(discriminator, out Type? dynamicType))
        {
            return dynamicType!;
        }
        if (CustomTypeNameResolver is not null)
        {
            Type? customType = CustomTypeNameResolver(GetDiscriminatorKey(discriminator));
            if (customType != null)
            {
                return customType;
            }
        }
        return typeof(global::JsonSubTypes.Aot.Generated.TestDomain.Game);
    }
    return typeof(global::JsonSubTypes.Aot.Generated.TestDomain.Game);
        }

        protected override void WriteBaseObject(Utf8JsonWriter writer, global::JsonSubTypes.Aot.Generated.TestDomain.Game value, JsonSerializerOptions options)
        {
            writer.WriteStartObject();

            writer.WriteEndObject();
        }
        protected override global::JsonSubTypes.Aot.Generated.TestDomain.Game DeserializeBase(JsonElement root, JsonSerializerOptions options)
        {
            global::JsonSubTypes.Aot.Generated.TestDomain.Game instance = new global::JsonSubTypes.Aot.Generated.TestDomain.Game();

            return instance;
        }
        protected override bool TryWriteNestedObject(Utf8JsonWriter writer, global::JsonSubTypes.Aot.Generated.TestDomain.Game value, Type runtimeType, JsonSerializerOptions options)
        {

            return false;
        }
    }
}