// <auto-generated/>
#nullable enable

namespace JsonSubTypes.Aot.Generated
{
    /// <summary>Generated by JsonSubTypes.Aot. Shared converter instances to add to JsonSerializerOptions.Converters.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("JsonSubTypes.Aot", "1.0.0")]
    public static class JsonSubTypesAotConverters
    {
        public static readonly AnimalJsonSubTypesConverter Animal = new AnimalJsonSubTypesConverter();
        public static readonly PersonJsonSubTypesConverter Person = new PersonJsonSubTypesConverter();
        public static readonly GadgetJsonSubTypesConverter Gadget = new GadgetJsonSubTypesConverter();
        public static readonly DottedGadgetJsonSubTypesConverter DottedGadget = new DottedGadgetJsonSubTypesConverter();
        public static readonly PayloadJsonSubTypesConverter Payload = new PayloadJsonSubTypesConverter();
        public static readonly GameJsonSubTypesConverter Game = new GameJsonSubTypesConverter();
    }
}