#nullable enable
using System;
using System.Linq;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace JsonSubTypes.Aot.Generated
{
    /// <summary>Generated by JsonSubTypes.Aot. Shared converter skeleton: Read, the dynamic-subtype machinery and the base-object helpers live here once so every converter test exercises them.</summary>
    public abstract class JsonSubTypesAotConverterBase<T> : JsonConverter<T> where T : class
    {
        public sealed override bool CanConvert(Type typeToConvert) => typeToConvert == typeof(T);

        public sealed override T? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            if (reader.TokenType == JsonTokenType.Null)
            {
                return null;
            }
            if (reader.TokenType != JsonTokenType.StartObject)
            {
                throw new JsonException("Unrecognized token: " + reader.TokenType);
            }
            using JsonDocument document = JsonDocument.ParseValue(ref reader);
            JsonElement root = document.RootElement;
            Type target = SelectType(root, options);
            if (target == typeof(T))
            {
                return DeserializeBase(root, options);
            }
            return (T?)JsonSerializer.Deserialize(root.GetRawText(), options.GetTypeInfo(target));
        }

        // Presence-mode write: the base object is written through WriteBaseObject,
        // registered subtypes through their own resolver-provided converters, and
        // unknown types through the type info resolver. Value-mode converters
        // override Write to inject the discriminator.
        public override void Write(Utf8JsonWriter writer, T value, JsonSerializerOptions options)
        {
            if (value is null)
            {
                writer.WriteNullValue();
                return;
            }
            Type runtimeType = value.GetType();
            if (runtimeType == typeof(T))
            {
                WriteBaseObject(writer, value, options);
                return;
            }
            JsonSerializer.Serialize(writer, value, options.GetTypeInfo(runtimeType));
        }

        protected abstract Type SelectType(JsonElement root, JsonSerializerOptions options);
        protected abstract T DeserializeBase(JsonElement root, JsonSerializerOptions options);
        protected abstract void WriteBaseObject(Utf8JsonWriter writer, T value, JsonSerializerOptions options);
        protected abstract bool TryWriteNestedObject(Utf8JsonWriter writer, T value, Type runtimeType, JsonSerializerOptions options);

        // Discriminator property name used by the dynamic write path; unused by
        // presence-mode converters.
        protected virtual string DiscriminatorPropertyName => "";

        public System.Collections.Concurrent.ConcurrentDictionary<object, Type> DynamicSubtypes { get; } = new System.Collections.Concurrent.ConcurrentDictionary<object, Type>();
        private readonly System.Collections.Concurrent.ConcurrentDictionary<Type, object> _dynamicReverse = new System.Collections.Concurrent.ConcurrentDictionary<Type, object>();

        public void RegisterDynamicSubtype(object discriminator, Type type)
        {
            DynamicSubtypes[discriminator] = type;
            _dynamicReverse[type] = discriminator; // last registration wins, like the builder
        }

        /// <summary>
        /// Custom discriminator-to-type resolution hook, invoked after the static
        /// registrations and DynamicSubtypes. Assign it to implement your own
        /// name-based lookup (e.g. assembly scanning, a DI registry). The resolved
        /// type must be resolvable by the TypeInfoResolver (in the source-gen context
        /// for Native AOT).
        /// </summary>
        public Func<object?, Type?>? CustomTypeNameResolver { get; set; }

        protected static object? GetDiscriminatorKey(JsonElement discriminator)
        {
            switch (discriminator.ValueKind)
            {
                case JsonValueKind.String:
                    return discriminator.GetString();
                case JsonValueKind.Number when int.TryParse(discriminator.GetRawText(), out int keyInt):
                    return keyInt;
                default:
                    return discriminator.GetRawText();
            }
        }

        protected bool TryGetDynamicType(JsonElement discriminator, out Type? dynamicType)
        {
            switch (discriminator.ValueKind)
            {
                case JsonValueKind.String:
                    return DynamicSubtypes.TryGetValue(discriminator.GetString()!, out dynamicType);
                case JsonValueKind.Number:
                    if (int.TryParse(discriminator.GetRawText(), out int dynamicInt) && DynamicSubtypes.TryGetValue(dynamicInt, out dynamicType))
                    {
                        return true;
                    }
                    return DynamicSubtypes.TryGetValue(discriminator.GetRawText(), out dynamicType);
                default:
                    return DynamicSubtypes.TryGetValue(discriminator.GetRawText(), out dynamicType);
            }
        }

        protected bool TryWriteDynamic(Utf8JsonWriter writer, T value, Type runtimeType, JsonSerializerOptions options)
        {
            if (_dynamicReverse.TryGetValue(runtimeType, out object? dynamicDiscriminator))
            {
                writer.WriteStartObject();
                string dynamicDiscriminatorName = DiscriminatorPropertyName;
                if (options.PropertyNamingPolicy != null)
                {
                    dynamicDiscriminatorName = options.PropertyNamingPolicy.ConvertName(dynamicDiscriminatorName);
                }
                writer.WritePropertyName(dynamicDiscriminatorName);
                writer.WriteRawValue(JsonSerializer.Serialize(dynamicDiscriminator, options.GetTypeInfo(dynamicDiscriminator.GetType())));
                string payload = JsonSerializer.Serialize(value, options.GetTypeInfo(runtimeType));
                using JsonDocument payloadDocument = JsonDocument.Parse(payload);
                foreach (JsonProperty property in payloadDocument.RootElement.EnumerateObject())
                {
                    property.WriteTo(writer);
                }
                writer.WriteEndObject();
                return true;
            }
            return false;
        }

        protected string SerializeBasePayload(T value, JsonSerializerOptions options)
        {
            using System.IO.MemoryStream stream = new System.IO.MemoryStream();
            using (Utf8JsonWriter writer = new Utf8JsonWriter(stream))
            {
                WriteBaseObject(writer, value, options);
            }
            return System.Text.Encoding.UTF8.GetString(stream.ToArray());
        }

        protected static bool TryGetProperty(JsonElement root, string name, JsonSerializerOptions options, out JsonElement value)
        {
            if (root.TryGetProperty(name, out value))
            {
                return true;
            }
            string? convertedName = options.PropertyNamingPolicy?.ConvertName(name);
            if (convertedName != null && convertedName != name && root.TryGetProperty(convertedName, out value))
            {
                return true;
            }
            if (options.PropertyNameCaseInsensitive)
            {
                foreach (JsonProperty property in root.EnumerateObject().Where(p => string.Equals(p.Name, name, StringComparison.OrdinalIgnoreCase)))
                {
                    value = property.Value;
                    return true;
                }
            }
            return false;
        }

        protected static bool TryGetValueInJson(JsonElement root, string propertyName, JsonSerializerOptions options, out JsonElement value)
        {
            if (TryGetProperty(root, propertyName, options, out value))
            {
                return true;
            }
            if (propertyName.Contains('.'))
            {
                string[] segments = propertyName.Split('.');
                JsonElement current = root;
                foreach (string segment in segments)
                {
                    if (!TryGetProperty(current, segment, options, out current))
                    {
                        value = default;
                        return false;
                    }
                }
                value = current;
                return true;
            }
            return false;
        }
    }

    /// <summary>Generated by JsonSubTypes.Aot. Value-mode converter skeleton: adds the discriminator-injection Write on top of JsonSubTypesAotConverterBase.</summary>
    public abstract class JsonSubTypesAotValueConverterBase<T> : JsonSubTypesAotConverterBase<T> where T : class
    {
        public sealed override void Write(Utf8JsonWriter writer, T value, JsonSerializerOptions options)
        {
            if (value is null)
            {
                writer.WriteNullValue();
                return;
            }

            Type runtimeType = value.GetType();
            if (!TryGetPayload(writer, value, runtimeType, options, out string payload))
            {
                return;
            }

            using JsonDocument payloadDocument = JsonDocument.Parse(payload);
            string discriminatorName = options.PropertyNamingPolicy?.ConvertName(DiscriminatorPropertyName) ?? DiscriminatorPropertyName;
            writer.WriteStartObject();
            if (AddDiscriminatorFirst)
            {
                writer.WritePropertyName(discriminatorName);
                WriteDiscriminatorValue(writer, runtimeType, options);
            }
            foreach (JsonProperty property in payloadDocument.RootElement.EnumerateObject().Where(p => !p.NameEquals(discriminatorName)))
            {
                property.WriteTo(writer);
            }
            if (!AddDiscriminatorFirst)
            {
                writer.WritePropertyName(discriminatorName);
                WriteDiscriminatorValue(writer, runtimeType, options);
            }
            writer.WriteEndObject();
        }

        // Resolves the serialized payload of the runtime type. Returns false
        // when the value was already written directly (base fallback, nested
        // chain, dynamic subtype or unregistered runtime type).
        private bool TryGetPayload(Utf8JsonWriter writer, T value, Type runtimeType, JsonSerializerOptions options, out string payload)
        {
            payload = "";
            if (runtimeType == typeof(T))
            {
                if (IsRegistered(runtimeType))
                {
                    payload = SerializeBasePayload(value, options);
                    return true;
                }
                WriteBaseObject(writer, value, options);
                return false;
            }
            if (IsRegistered(runtimeType))
            {
                payload = JsonSerializer.Serialize(value, options.GetTypeInfo(runtimeType));
                return true;
            }
            if (TryWriteNestedObject(writer, value, runtimeType, options))
            {
                return false;
            }
            if (TryWriteDynamic(writer, value, runtimeType, options))
            {
                return false;
            }
            JsonSerializer.Serialize(writer, value, options.GetTypeInfo(runtimeType));
            return false;
        }

        protected virtual System.Collections.Generic.Dictionary<System.Type, System.Action<Utf8JsonWriter, JsonSerializerOptions>> DiscriminatorWriters { get; } = new System.Collections.Generic.Dictionary<System.Type, System.Action<Utf8JsonWriter, JsonSerializerOptions>>();

        protected bool IsRegistered(Type runtimeType)
        {
            return DiscriminatorWriters.ContainsKey(runtimeType);
        }

        protected virtual bool AddDiscriminatorFirst => true;

        private void WriteDiscriminatorValue(Utf8JsonWriter writer, Type runtimeType, JsonSerializerOptions options)
        {
            if (DiscriminatorWriters.TryGetValue(runtimeType, out System.Action<Utf8JsonWriter, JsonSerializerOptions>? write))
            {
                write(writer, options);
                return;
            }
            throw new JsonException("Impossible to serialize type: " + runtimeType.FullName + " because there is no registered mapping for the discriminator property");
        }
    }
}