#nullable enable
using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace JsonSubTypes.Aot.Generated
{
    /// <summary>Generated by JsonSubTypes.Aot. Compiled converter for global::JsonSubTypes.Aot.Generated.TestDomain.Payload.</summary>
    public sealed class PayloadJsonSubTypesConverter : JsonSubTypesAotValueConverterBase<global::JsonSubTypes.Aot.Generated.TestDomain.Payload>
    {
        protected override string DiscriminatorPropertyName => "$PayloadKind";

        protected override System.Collections.Generic.Dictionary<System.Type, System.Action<Utf8JsonWriter, JsonSerializerOptions>> DiscriminatorWriters { get; } = new System.Collections.Generic.Dictionary<System.Type, System.Action<Utf8JsonWriter, JsonSerializerOptions>>
        {
            [typeof(global::JsonSubTypes.Aot.Generated.TestDomain.Game)] = static (writer, options) => writer.WriteRawValue(JsonSerializer.Serialize(global::JsonSubTypes.Aot.Generated.TestDomain.PayloadDiscriminator.GAME, options.GetTypeInfo(typeof(global::JsonSubTypes.Aot.Generated.TestDomain.PayloadDiscriminator)))),
            [typeof(global::JsonSubTypes.Aot.Generated.TestDomain.Com)] = static (writer, options) => writer.WriteRawValue(JsonSerializer.Serialize(global::JsonSubTypes.Aot.Generated.TestDomain.PayloadDiscriminator.COM, options.GetTypeInfo(typeof(global::JsonSubTypes.Aot.Generated.TestDomain.PayloadDiscriminator))))
        };

        protected override Type SelectType(JsonElement root, JsonSerializerOptions options)
        {
    if (TryGetValueInJson(root, "$PayloadKind", options, out JsonElement discriminator))
    {

    if (discriminator.ValueKind == JsonValueKind.String)
    {
        switch (discriminator.GetString())
        {
                        case "GAME": return typeof(global::JsonSubTypes.Aot.Generated.TestDomain.Game);
                        case "COM": return typeof(global::JsonSubTypes.Aot.Generated.TestDomain.Com);
        }
    }
    if (discriminator.ValueKind == JsonValueKind.Number)
    {
        switch (discriminator.GetRawText())
        {
                        case "0": return typeof(global::JsonSubTypes.Aot.Generated.TestDomain.Game);
                        case "1": return typeof(global::JsonSubTypes.Aot.Generated.TestDomain.Com);
        }
    }
        if (TryGetDynamicType(discriminator, out Type? dynamicType))
        {
            return dynamicType!;
        }
        if (CustomTypeNameResolver is not null)
        {
            Type? customType = CustomTypeNameResolver(GetDiscriminatorKey(discriminator));
            if (customType != null)
            {
                return customType;
            }
        }
        return typeof(global::JsonSubTypes.Aot.Generated.TestDomain.Payload);
    }
    return typeof(global::JsonSubTypes.Aot.Generated.TestDomain.Payload);
        }

        protected override void WriteBaseObject(Utf8JsonWriter writer, global::JsonSubTypes.Aot.Generated.TestDomain.Payload value, JsonSerializerOptions options)
        {
            writer.WriteStartObject();

            writer.WriteEndObject();
        }
        protected override global::JsonSubTypes.Aot.Generated.TestDomain.Payload DeserializeBase(JsonElement root, JsonSerializerOptions options)
        {
            global::JsonSubTypes.Aot.Generated.TestDomain.Payload instance = new global::JsonSubTypes.Aot.Generated.TestDomain.Payload();

            return instance;
        }
        protected override bool TryWriteNestedObject(Utf8JsonWriter writer, global::JsonSubTypes.Aot.Generated.TestDomain.Payload value, Type runtimeType, JsonSerializerOptions options)
        {
        if (runtimeType == typeof(global::JsonSubTypes.Aot.Generated.TestDomain.Run))
        {
            writer.WriteStartObject();
                        writer.WritePropertyName("$PayloadKind");
                        writer.WriteRawValue(JsonSerializer.Serialize(global::JsonSubTypes.Aot.Generated.TestDomain.PayloadDiscriminator.GAME, options.GetTypeInfo(typeof(global::JsonSubTypes.Aot.Generated.TestDomain.PayloadDiscriminator))));
                        writer.WritePropertyName("$GameKind");
                        writer.WriteRawValue(JsonSerializer.Serialize(global::JsonSubTypes.Aot.Generated.TestDomain.GameDiscriminator.RUN, options.GetTypeInfo(typeof(global::JsonSubTypes.Aot.Generated.TestDomain.GameDiscriminator))));
            string payload = JsonSerializer.Serialize(value, options.GetTypeInfo(runtimeType));
            using JsonDocument payloadDocument = JsonDocument.Parse(payload);
            foreach (JsonProperty property in payloadDocument.RootElement.EnumerateObject())
            {
                property.WriteTo(writer);
            }
            writer.WriteEndObject();
            return true;
        }
        if (runtimeType == typeof(global::JsonSubTypes.Aot.Generated.TestDomain.Walk))
        {
            writer.WriteStartObject();
                        writer.WritePropertyName("$PayloadKind");
                        writer.WriteRawValue(JsonSerializer.Serialize(global::JsonSubTypes.Aot.Generated.TestDomain.PayloadDiscriminator.GAME, options.GetTypeInfo(typeof(global::JsonSubTypes.Aot.Generated.TestDomain.PayloadDiscriminator))));
                        writer.WritePropertyName("$GameKind");
                        writer.WriteRawValue(JsonSerializer.Serialize(global::JsonSubTypes.Aot.Generated.TestDomain.GameDiscriminator.WALK, options.GetTypeInfo(typeof(global::JsonSubTypes.Aot.Generated.TestDomain.GameDiscriminator))));
            string payload = JsonSerializer.Serialize(value, options.GetTypeInfo(runtimeType));
            using JsonDocument payloadDocument = JsonDocument.Parse(payload);
            foreach (JsonProperty property in payloadDocument.RootElement.EnumerateObject())
            {
                property.WriteTo(writer);
            }
            writer.WriteEndObject();
            return true;
        }
            return false;
        }
    }
}