#nullable enable
using System;
using System.Linq;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace JsonSubTypes.Aot.Generated
{
    /// <summary>Generated by JsonSubTypes.Aot. Compiled converter for global::JsonSubTypes.Aot.Generated.TestDomain.Person.</summary>
    public sealed class PersonJsonSubTypesConverter : JsonConverter<global::JsonSubTypes.Aot.Generated.TestDomain.Person>
    {
        public override bool CanConvert(Type typeToConvert) => typeToConvert == typeof(global::JsonSubTypes.Aot.Generated.TestDomain.Person);

        public override void Write(Utf8JsonWriter writer, global::JsonSubTypes.Aot.Generated.TestDomain.Person value, JsonSerializerOptions options)
        {
            if (value is null)
            {
                writer.WriteNullValue();
                return;
            }
            Type runtimeType = value.GetType();
            if (runtimeType == typeof(global::JsonSubTypes.Aot.Generated.TestDomain.Person))
            {
                WriteBaseObject(writer, (global::JsonSubTypes.Aot.Generated.TestDomain.Person)value, options);
                return;
            }
            JsonSerializer.Serialize(writer, value, options.GetTypeInfo(runtimeType));
        }

        public override global::JsonSubTypes.Aot.Generated.TestDomain.Person? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            if (reader.TokenType == JsonTokenType.Null)
            {
                return null;
            }
            if (reader.TokenType != JsonTokenType.StartObject)
            {
                throw new JsonException("Unrecognized token: " + reader.TokenType);
            }
            using JsonDocument document = JsonDocument.ParseValue(ref reader);
            JsonElement root = document.RootElement;
            Type target = SelectType(root, options);
            if (target == typeof(global::JsonSubTypes.Aot.Generated.TestDomain.Person))
            {
                return DeserializeBase(root, options);
            }
            return (global::JsonSubTypes.Aot.Generated.TestDomain.Person?)JsonSerializer.Deserialize(root.GetRawText(), options.GetTypeInfo(target));
        }

        private Type SelectType(JsonElement root, JsonSerializerOptions options)
        {
    System.Collections.Generic.HashSet<Type> matches = new System.Collections.Generic.HashSet<Type>();
if (root.TryGetProperty("JobTitle", out _))
{
    matches.Add(typeof(global::JsonSubTypes.Aot.Generated.TestDomain.Employee));
}
if (root.TryGetProperty("Skill", out _))
{
    matches.Add(typeof(global::JsonSubTypes.Aot.Generated.TestDomain.Artist));
}
    if (matches.Count == 1)
    {
        return matches.First();
    }
    if (matches.Count > 1)
    {
        throw new JsonException("Ambiguous type resolution, expected only one type but got: " + string.Join(", ", matches.Select(t => t.FullName)));
    }
    return typeof(global::JsonSubTypes.Aot.Generated.TestDomain.Person);
        }


    private static string SerializeBasePayload(global::JsonSubTypes.Aot.Generated.TestDomain.Person value, JsonSerializerOptions options)
    {
        using System.IO.MemoryStream stream = new System.IO.MemoryStream();
        using (Utf8JsonWriter writer = new Utf8JsonWriter(stream))
        {
            WriteBaseObject(writer, value, options);
        }
        return System.Text.Encoding.UTF8.GetString(stream.ToArray());
    }

    private static void WriteBaseObject(Utf8JsonWriter writer, global::JsonSubTypes.Aot.Generated.TestDomain.Person value, JsonSerializerOptions options)
    {
        writer.WriteStartObject();
    string nameFirstName = "FirstName";
    if (options.PropertyNamingPolicy != null && true)
    {
        nameFirstName = options.PropertyNamingPolicy.ConvertName(nameFirstName);
    }
    writer.WritePropertyName(nameFirstName);
    JsonSerializer.Serialize(writer, value.FirstName, options.GetTypeInfo(typeof(string)));
        writer.WriteEndObject();
    }

    private static global::JsonSubTypes.Aot.Generated.TestDomain.Person DeserializeBase(JsonElement root, JsonSerializerOptions options)
    {
        global::JsonSubTypes.Aot.Generated.TestDomain.Person instance = new global::JsonSubTypes.Aot.Generated.TestDomain.Person();
    if (TryGetProperty(root, "FirstName", options, out JsonElement FirstNameValue))
    {
        instance.FirstName = (string)JsonSerializer.Deserialize(FirstNameValue.GetRawText(), options.GetTypeInfo(typeof(string)))!;
    }
        return instance;
    }

    private static bool TryGetProperty(JsonElement root, string name, JsonSerializerOptions options, out JsonElement value)
    {
        if (root.TryGetProperty(name, out value))
        {
            return true;
        }
        string? convertedName = options.PropertyNamingPolicy?.ConvertName(name);
        if (convertedName != null && convertedName != name && root.TryGetProperty(convertedName, out value))
        {
            return true;
        }
        if (options.PropertyNameCaseInsensitive)
        {
            foreach (JsonProperty property in root.EnumerateObject())
            {
                if (string.Equals(property.Name, name, StringComparison.OrdinalIgnoreCase))
                {
                    value = property.Value;
                    return true;
                }
            }
        }
        return false;
    }

    private static bool TryGetValueInJson(JsonElement root, string propertyName, JsonSerializerOptions options, out JsonElement value)
    {
        if (TryGetProperty(root, propertyName, options, out value))
        {
            return true;
        }
        if (propertyName.IndexOf('.') >= 0)
        {
            string[] segments = propertyName.Split('.');
            JsonElement current = root;
            foreach (string segment in segments)
            {
                if (!TryGetProperty(current, segment, options, out current))
                {
                    value = default;
                    return false;
                }
            }
            value = current;
            return true;
        }
        return false;
    }
    }
}