<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\JsonSubTypes.Text.Json.Tests.Shared\JsonSubTypes.Text.Json.Tests.Shared.csproj" />
  </ItemGroup>
</Project>
